[tool.poetry]
name = "depin-test"
version = "0.1.0"
description = ""
authors = ["Alex <alex@toriai.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
locust = "^2.22.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
